version: '3.8'

services:
  api:
    build: 
      context: .
      args:
        - ENABLE_AI_FEATURES=${ENABLE_AI_FEATURES:-true}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      # Persist AI model cache
      - ai_models_cache:/root/.cache/huggingface
    environment:
      - DATABASE_URL=sqlite:///./notes_app.db
      - ENABLE_AI_FEATURES=${ENABLE_AI_FEATURES:-true}
    command: >
      bash -c "python initialize_db.py && 
              uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  # Uncomment to add a PostgreSQL database
  # db:
  #   image: postgres:14
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=notes_db
  #   ports:
  #     - "5432:5432"

volumes:
  # Volume for caching AI models
  ai_models_cache:
  # Uncomment if using PostgreSQL
  # postgres_data:
